# A config that grabs everything from git

[minidump-stackwalk]
git = "https://github.com/rust-minidump/rust-minidump"
# branch = "mybranch"
# rev = "a525b3fe40495680a5c4984f8d1223963583f894"
# tag = "0.11.0"

[dump_syms]
git = "https://github.com/mozilla/dump_syms"
# branch = "mybranch"
# rev = "3977a09ab0aee64d87597da47bb9fdf29ffe82c5"
# tag = "v1.0.1"

[minidumper-test]
force_build = true
git = "https://github.com/EmbarkStudios/crash-handling"
# branch = "mybranch"
# rev = "6ff595e0e809ab5028bf76d22c4fb036ed4ffa6e"
# tag = "0.3.1"

[minidumper-test]
force_build = true
git = "https://github.com/EmbarkStudios/crash-handling"