# Pipeline files are passed via --config to minidump-pipeline,
# with `pipeline.toml` being the implicit default one.
#
# These files are basically Cargo.toml dependencies, that minidump-pipeline
# will use to fetch binaries, either with `cargo install` or `cargo build`.



# [my-example-dep]
# # via crates.io (the default, if version not specified, uses latest):
# version = "1.0.1"
#
#
# # via git (only `git` is required)
# git = "https://github.com/rust-minidump/rust-minidump"
# branch = "mybranch"
# rev = "a525b3fe40495680a5c4984f8d1223963583f894"
# tag = "0.11.0"
#
#
# # via path (will use cargo build to avoid excessive rebuilds)
# path = "../rust-minidump/minidump-stackwalk



[minidump-stackwalk]
# git = "https://github.com/rust-minidump/rust-minidump"
# path = "../rust-minidump/minidump-stackwalk/"

# optional! (only used when you pass --debugger)
[minidump-debugger]
# git = "https://github.com/Gankra/minidump-debugger"
# path = "../minidump-debugger/"

[dump_syms]
# git = "https://github.com/mozilla/dump_syms"
# path = "../dump_syms/"



# these two need to be by git because they aren't published
# and we need to force_build because we want their symbols!

[minidumper-test]
force_build = true
git = "https://github.com/EmbarkStudios/crash-handling"
# path = "../crash-handling/minidumper-test"

[crash-client]
force_build = true
git = "https://github.com/EmbarkStudios/crash-handling"
# path = "../crash-handling/minidumper-test/crash-client"
