# A config with the old (non-v0) mangling

# inlines = true
# rust-mangling = "v0"



[minidump-stackwalk]
# path = "../rust-minidump/minidump-stackwalk/"

# optional! (only used when you pass --debugger)
[minidump-debugger]
# path = "../minidump-debugger/"

[dump_syms]
# path = "../dump_syms/"



# these two need to be by git because they aren't published
# and we need to force_build because we want their symbols!

[minidumper-test]
git = "https://github.com/EmbarkStudios/crash-handling"
# path = "../crash-handling/minidumper-test"

[crash-client]
force_build = true
git = "https://github.com/EmbarkStudios/crash-handling"
# path = "../crash-handling/minidumper-test/crash-client"
