# A config for testing the inlining feature

inlines = true
rust-mangling = "v0"



[minidump-stackwalk]
# git = "https://github.com/Gankra/rust-minidump"
# branch = "inline"
# path = "../rust-minidump/minidump-stackwalk/"

# optional! (only used when you pass --debugger)
[minidump-debugger]
# git = "https://github.com/Gankra/minidump-debugger"
# path = "../minidump-debugger/"

[dump_syms]
git = "https://github.com/mozilla/dump_syms"
# rev = "54f9e6240e34cf17fc7dc60ac4985772e2c20001"
# path = "../dump_syms/"



# these two need to be by git because they aren't published
# and we need to force_build because we want their symbols!

[minidumper-test]
git = "https://github.com/EmbarkStudios/crash-handling"
# path = "../crash-handling/minidumper-test"

[crash-client]
force_build = true
git = "https://github.com/EmbarkStudios/crash-handling"
# path = "../crash-handling/minidumper-test/crash-client"
